# Generated by Django 3.2.15 on 2022-10-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AAS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceImages',
            new_name='AttendanceImage',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
