# Generated by Django 3.0.14 on 2022-12-25 16:23

import AAS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=AAS.models.filepath),
        ),
    ]
