# Generated by Django 3.2.15 on 2022-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAS', '0002_auto_20221024_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('utype', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=520)),
                ('date', models.DateField()),
            ],
        ),
    ]
